version: '3.8'

services:
  # Database MongoDB
  db:
    image: mongo:latest
    container_name: iot_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database/data:/data/db

  # Backend FastAPI/Flask
  backend:
    build: ./backend
    container_name: iot_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017

  # Frontend React
  frontend:
    build: ./frontend
    container_name: iot_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend